# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies and build
COPY package.json tsconfig.json ./
COPY src ./src

RUN npm install && npm run build && npm prune --production

# Set production environment
ENV NODE_ENV=production

# Expose port - standard for stdio not needed but conventionally
# ENTRYPOINT to start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
